# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Soma Cultura
author: Daniela Lopez Vives
email: daniela@somaculturatherapy.com
description: >- # this means to ignore newlines until "baseurl:"
  Soma Cultura is a virtual mental-health therapy practice that provides services to adult (18+ years) clients that speak English or Spanish.
baseurl: /soma-cultura/ # the subpath of your site, e.g. /blog
domain: nstauder2.github.io
url: https://nstauder2.github.io # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
linkedin_username:  daniela-lopez-vives-52591293

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-remote-theme


languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true

#sass:
#  sourcemap: never

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
